## Numpy

In [2]:
import numpy as np

## Create a 3x3x3 array with random values 

In [3]:
x = np.random.random((3,3,3))

print(x)
print(x.shape)

[[[0.69493806 0.11867039 0.76577398]
  [0.90505587 0.19873791 0.70350411]
  [0.35489261 0.32335684 0.95352481]]

 [[0.49493113 0.13946142 0.58737045]
  [0.25762275 0.37611852 0.71793581]
  [0.68153546 0.77571695 0.09526304]]

 [[0.74585917 0.83002576 0.12506117]
  [0.08900569 0.72795292 0.18794776]
  [0.40241556 0.5748254  0.12916349]]]
(3, 3, 3)


## Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [4]:
x = np.diag([1,2,3,4],-1)
print(x)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


## Create a 8x8 matrix and fill it with a checker-board pattern

In [5]:
x = np.zeros((8,8),dtype = int)

x[1::2,::2] = 1
x[::2,1::2] = 1

print(x)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


## Normalize a 5x5 random matrix

In [6]:
x= np.random.random((5,5))

xmax, xmin = x.max(), x.min()
x = (x - xmin)/(xmax - xmin)

print(x)

[[0.37401778 0.51433561 0.55755688 0.46553686 0.93141009]
 [0.58471993 0.29753256 0.57936411 0.68032204 0.4709351 ]
 [0.3535105  0.81299333 0.39289144 0.         0.44328793]
 [1.         0.38161706 0.31103367 0.26500068 0.84251147]
 [0.31514269 0.50754797 0.75893262 0.99503981 0.77475139]]


## Find common values between two arrays

In [9]:
arr1 = np.array([0, 10, 20, 40, 60])

arr2 = np.array([10, 30, 40])

print(np.intersect1d(arr1, arr2))

[10 40]


## Get the dates of yesterday, today and tomorrow

In [10]:
yesterday = np.datetime64('today') - np.timedelta64(1)
print("Yesterday: ",yesterday)

today     = np.datetime64('today')
print("Today: ",today)

tomorrow  = np.datetime64('today') + np.timedelta64(1)
print("Tomorrow: ",tomorrow)

Yesterday:  2020-07-29
Today:  2020-07-30
Tomorrow:  2020-07-31


## Consider two random array A and B, check if they are equal

In [12]:
x = np.random.randint(0,3,6)
print(x)

y = np.random.randint(0,3,6)
print(y)

arr_equal = np.allclose(x, y)
print(arr_equal)

[1 0 2 0 1 1]
[2 1 0 0 1 1]
False


## Create random vector of size 10 and replace the maximum value by 0

In [14]:
x = np.random.random(10)
print(x)

x[x.argmax()] = 0

print("Max value after getting replaced by 0:")
print(x)

[0.07540449 0.95905473 0.1909742  0.34773467 0.83616119 0.29517742
 0.4602414  0.63513764 0.73331313 0.68652534]
Max value after getting replaced by 0:
[0.07540449 0.         0.1909742  0.34773467 0.83616119 0.29517742
 0.4602414  0.63513764 0.73331313 0.68652534]


## Print all the values of an array

In [15]:
x = np.set_printoptions(threshold=float("inf"))
x = np.zeros((16,16))
print(x)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


## Subtract the mean of each row of a matrix

In [16]:
x = np.random.rand(5, 10)
print(x)

y = x - x.mean(axis=1, keepdims=True)

print(y)

[[0.14581856 0.15355549 0.79059066 0.81297291 0.95885485 0.80685148
  0.53835749 0.83229207 0.68682102 0.01687852]
 [0.17103119 0.48008502 0.4683178  0.58997893 0.04809995 0.57893382
  0.31824256 0.5089116  0.56152934 0.07107695]
 [0.34934974 0.4627351  0.01695905 0.66720901 0.04980089 0.022028
  0.3068177  0.790424   0.1608805  0.08715476]
 [0.14104608 0.99386945 0.33230183 0.03013478 0.64273152 0.76296677
  0.95529125 0.75277613 0.56061235 0.21503024]
 [0.63588863 0.14439851 0.10630075 0.17382655 0.46027375 0.53384265
  0.7220405  0.35495135 0.17467683 0.73975541]]
[[-0.42848075 -0.42074381  0.21629136  0.2386736   0.38455555  0.23255217
  -0.03594181  0.25799276  0.11252171 -0.55742079]
 [-0.20858952  0.1004643   0.08869709  0.21035821 -0.33152077  0.1993131
  -0.06137815  0.12929089  0.18190862 -0.30854377]
 [ 0.05801386  0.17139922 -0.27437683  0.37587313 -0.24153498 -0.26930788
   0.01548183  0.49908813 -0.13045537 -0.20418111]
 [-0.39762996  0.45519341 -0.20637421 -0.50854126  0

## Consider a given vector, add 1 to each element indexed by a second vector

In [18]:
x = np.ones(10)
y = np.random.randint(0,len(x),20)
x += np.bincount(y, minlength=len(x))
print(x)

[4. 3. 1. 3. 2. 3. 6. 3. 2. 3.]


## Get the diagonal of a dot product

In [34]:
x = np.random.rand(5, 5)
print(x)
y = np.random.rand(5, 5)
print(y)
z = np.dot(x,y).diagonal()
print(z)

[[0.53699528 0.68396141 0.93217974 0.78858461 0.72687059]
 [0.3982723  0.10977761 0.87674548 0.861809   0.24536142]
 [0.54832591 0.33043261 0.03388396 0.29834112 0.0880128 ]
 [0.60874923 0.34524382 0.40217554 0.73526464 0.65622664]
 [0.88192422 0.13375732 0.79905009 0.55515442 0.01618558]]
[[0.09608609 0.11489123 0.12655463 0.76592003 0.41972517]
 [0.21307919 0.07310331 0.31074894 0.85502865 0.83800473]
 [0.82825339 0.20129143 0.5871445  0.84671863 0.28994579]
 [0.97698578 0.97986256 0.04736006 0.75008968 0.33200788]
 [0.05606925 0.49159789 0.10073302 0.3376561  0.81305357]]
[1.78060779 1.19533798 0.21496479 1.87506945 0.91141166]


## Find the most frequent value in an array

In [19]:
x = np.random.randint(0, 10, 40)
print(x)

print(np.bincount(x).argmax())

[6 6 9 9 1 1 0 5 3 8 7 5 5 4 4 7 6 2 2 5 2 4 4 8 6 6 2 3 9 5 6 3 5 7 3 5 0
 6 7 9]
5


## Get the n largest values of an array

In [23]:
x = np.arange(15)
print(x)

np.random.shuffle(x)
n = 3

print (x[np.argsort(x)[-n:]])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[12 13 14]


## Create a record array from a regular array

In [24]:
x=np.array([1,2,3,4])
y=np.array(['Red','Green','White','Orange'])
z=np.array([12.20,15,20,40])

result= np.core.records.fromarrays([x,y,z],names='a,b,c')

print(result[0])
print(result[1])
print(result[2])

(1, 'Red', 12.2)
(2, 'Green', 15.)
(3, 'White', 20.)
